void eangle2a(int);
void eangle2a_fixed(int);
void eangle2b(int);
void eangle3(int, double (*)[3]);
void eangle(void);
void eangle1(void);
void eangle2(int);
//double acos(double);
int is_ring43(int, int, int);
int is_ring53(int, int, int);
int is_ring63(int, int, int);
int is_delocalbond(int, int);
int is_TS(int, int, int);
int isbond(int,int);
int find_bond(int,int);
void transtheta(int *, float *, float *, char *, char *, char *, char *);
void ts_four(int *, float *, float *,char *, char *,char *,char *);
long ipack(int ,int ,int ,int);
long kang(int,int,int);
void numeral(int,char *,int);
