int find_bond(int,int);
int find_fixed_bond(int,int);
void bnd_corr(int,int, int,int,double *);
double dihdrl(int,int,int,int);
double deltaks(double,double);
void ebond(void);
void ebond1(void);
void ebond2(int);

FILE * fopen_path ( char * , char * , char * ) ;
void find_pibond(int *,char *, float *,float *,float *,float *,float *);
void find_metalbond(int *, int, int,char *,float *, float *);
void angle(int ,int ,int ,float *);
int is_ring31(int);
int is_ring41(int);
int is_ring51(int);
int is_ring61(int);
int is_ring42(int, int);
int is_ring52(int, int);
int is_ring62(int,int);
void pcmfout(int);
double arcos(float );
double angs(float,float,float,float,float ,float ,float ,float);
double powi(double, int);
void numeral(int, char *, int);
int is_delocalbond(int ia, int ib);
void message_alert(char *, char *);
double sign(double ,double  ); 
void transbond(int *,char *,float *,float *);
int is_bond(int,int);
double deltaks(double,double);
float get_bond(int, int);
void set_missing_constants(int);        
int get_missing_constants(void);
int kbond(void);
void kstrtor(void);
void kstrbnd(void);
void kvdw(void);
