int FetchRecord(FILE *, char *);
void initialize_pcmodel(void);
void mmp22mod(int,int);
void mm32mod(int,int);
void pcmfin(int, int);
void initialize(void);
void mmxsub(int);
void check_numfile(int, char *);
void read_sdf(int,int);
void type(void);
void initialize_gmmx(void);
void read_gmmxinp(void);
void run_gmmx(void);
void parse_control(char *);
void initialize_control(void);
void get_errfile(void);
FILE * fopen_path ( char * , char * , char * ) ;
void pcmfout(int);
void gettoken(void);
void check_str(void);
void find_rings(void);
