void message_alert(char *,char *);
void find_rings1(int *, int **);
void del_atom(int, int **);
void log_ring1(int, int *);
int icompare(int, int *, int *);
int in_ring(int,int);
void add_all_rings(int,int *);
void trim(int ,int *,int *);
void check_N2(int,int *,int *);
void getUnion(int *, int *,int *);
int getRing(int,int,int *, int **,int *);
void delete_bond(int,int, int **);
void breakBond(int,int **);
void repack(int,int **);
void addq(int,int *,int);
int deleteq(int *,int);
void add_pair(int ,int ,int,int);
void find_rings(void);
int get_intersection(int *, int *);
