FILE * fopen_path ( char * , char * , char * ) ;
void InitialTransform(void);
void zero_data(void);
void read_datafiles(char *);
void initialize_pcmodel(void);
void fixdisreset(void);
void coordreset(void);
void ddrivereset(void);
void hbondreset(void);
void pireset(void);
void generate_bonds(void);
void set_field(void);
void fixangle_reset(void);
void message_alert(char *, char *);
int strmessage_alert(char *);
void gettoken(void);
void free_dotmem(void);
void init_pov(void);
void reset_fixtype(void);
void set_window_title(void);
void remove_file(char *,char *);
void reset_calc_parameters(void);
void reset_atom_data(void);
void initialize(void);
void resetsubstrmem(void);
