void densty(int, float **x, float **y, float);
void printarray(float a[], char *s);
void printmatrix(float **, char *s);
double sign(double a,double b );
void linear(float **, float *, int);
void square(float *, float **, int);
void scfchk(int, int, int *,float *);
void diag(int,float **);
void frag_diag(float **, float **, float *);
void xdiag(int,float **, float **, float *);
void fofgen(float **,float **,float **, float **, int *, float **);
void otable(void);
void message_alert(char *,char *);
void vescf(void);
void printcont(float **,int,int,char *);
void randnum(long int *,float *);
